name: PlayLegendBan
version: 1.0
main: de.eric.ban.Ban

commands:
  ban:
    description: bans a player
    aliases:
      - punish
    permission: ban.ban
    usage: /command <player> <reason> (<time>)
  unban:
    description: unbans a player
    alias:
      - pardon
    permission: ban.unban
    usage: /command <player>